from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from models.types.approach_retract import ApproachAxisRef, ApproachRetractConfig, ApproachRetractStep
from models.types.motion_approximation import ApproximationMode, MotionApproximation

# Header KRL par défaut : tout ce qui précède le premier mouvement (hors $APO/$VEL/$BASE/$TOOL,
# générés depuis les réglages). Tokens substitués à la génération : {PROGRAM_NAME}, {DATE},
# {BASE}, {TOOL}, {VEL_CP}, {N_MOTIONS}. Le DEF doit porter le nom du programme (exigence KUKA).
DEFAULT_KUKA_HEADER = """&ACCESS RVP
&REL 1
&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe
&PARAM EDITMASK = *
DEF {PROGRAM_NAME} ( )


; GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )
; INTERRUPT ON 3

;FOLD Initialise and set default speed
BAS (#INITMOV,0)
BAS (#VEL_PTP,20)
BAS (#ACC_PTP,20)
$VEL.CP=0.2
BAS (#TOOL,0)
BAS (#BASE,0)
;ENDFOLD

;;FOLD STARTPOS
;$BWDSTART = FALSE
;PDAT_ACT = PDEFAULT
;BAS(#PTP_DAT)
;FDAT_ACT = {TOOL_NO 0,BASE_NO 0,IPO_FRAME #BASE}
;BAS(#FRAMES)
;;ENDFOLD

$ADVANCE = 5

;FOLD ---- Quickly skip BCO ----
; PTP $AXIS_ACT
;ENDFOLD

; Program generated by CalibraX on {DATE}"""


@dataclass
class ProgramGenerationSettings:
    home_enabled: bool = True
    approach: ApproachRetractConfig = field(
        default_factory=ApproachRetractConfig.default_approach
    )
    retract: ApproachRetractConfig = field(
        default_factory=ApproachRetractConfig.default_retract
    )
    header_text: str = DEFAULT_KUKA_HEADER
    default_approximation: MotionApproximation = field(
        default_factory=lambda: MotionApproximation(mode=ApproximationMode.C_DIS, value=1.0)
    )
    # Vitesse constante imposée le long de la trajectoire (mm/s). None = vitesses du programme.
    constant_speed_mmps: float | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "home_enabled": self.home_enabled,
            "approach": _approach_retract_to_dict(self.approach),
            "retract": _approach_retract_to_dict(self.retract),
            "header_text": self.header_text,
            "default_approximation": _approximation_to_dict(self.default_approximation),
            "constant_speed_mmps": self.constant_speed_mmps,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> ProgramGenerationSettings:
        payload = data if isinstance(data, dict) else {}
        raw_speed = payload.get("constant_speed_mmps")
        return cls(
            home_enabled=bool(payload.get("home_enabled", True)),
            approach=_approach_retract_from_dict(
                payload.get("approach"), default=ApproachRetractConfig.default_approach()
            ),
            retract=_approach_retract_from_dict(
                payload.get("retract"), default=ApproachRetractConfig.default_retract()
            ),
            # Header vide (sessions antérieures) → header KUKA par défaut
            header_text=str(payload.get("header_text") or DEFAULT_KUKA_HEADER),
            default_approximation=(
                _approximation_from_dict(payload["default_approximation"])
                if "default_approximation" in payload
                else MotionApproximation(mode=ApproximationMode.C_DIS, value=1.0)
            ),
            constant_speed_mmps=float(raw_speed) if raw_speed is not None else None,
        )


def _approach_retract_to_dict(cfg: ApproachRetractConfig) -> dict[str, Any]:
    return {
        "enabled": cfg.enabled,
        "steps": [s.to_dict() for s in cfg.steps],
    }


def _approach_retract_from_dict(
    data: Any, default: ApproachRetractConfig
) -> ApproachRetractConfig:
    if not isinstance(data, dict):
        return default
    # Rétrocompatibilité : ancien format avec axis_ref/distance_mm/speed_mps directement
    if "steps" in data and isinstance(data["steps"], list):
        steps = tuple(
            ApproachRetractStep.from_dict(s)
            for s in data["steps"]
            if isinstance(s, dict)
        )
        if not steps:
            steps = default.steps
    elif "axis_ref" in data:
        steps = (ApproachRetractStep.from_dict(data),)
    else:
        steps = default.steps
    return ApproachRetractConfig(
        enabled=bool(data.get("enabled", default.enabled)),
        steps=steps,
    )


def _approximation_to_dict(approx: MotionApproximation) -> dict[str, Any]:
    return {"mode": approx.mode.value, "value": approx.value}


def _approximation_from_dict(data: Any) -> MotionApproximation:
    if not isinstance(data, dict):
        return MotionApproximation.none()
    try:
        mode = ApproximationMode(data.get("mode", "NONE"))
    except ValueError:
        mode = ApproximationMode.NONE
    return MotionApproximation(mode=mode, value=float(data.get("value", 0.0)))
